(cl:defpackage amrl_msgs-srv
  (:use )
  (:export
   "OBJECTDETECTIONSRV"
   "<OBJECTDETECTIONSRV-REQUEST>"
   "OBJECTDETECTIONSRV-REQUEST"
   "<OBJECTDETECTIONSRV-RESPONSE>"
   "OBJECTDETECTIONSRV-RESPONSE"
   "SOCIALPIPSSRV"
   "<SOCIALPIPSSRV-REQUEST>"
   "SOCIALPIPSSRV-REQUEST"
   "<SOCIALPIPSSRV-RESPONSE>"
   "SOCIALPIPSSRV-RESPONSE"
  ))

